[package]
name = "legend_of_mierda"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.10"
bevy_ecs_ldtk = "0.7"
bevy-inspector-egui = "0.18"
bevy_rapier2d = "0.21"
