[package]
name = "legend_of_mierda"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.11.2"
bevy_ecs_ldtk = "0.8"
bevy-inspector-egui = "0.19"
bevy_rapier2d = "0.22"
rand = "0.8.5"
belly = {git="https://github.com/jkb0o/belly.git", rev="0845c96cb2bb201586a7b8b3830af0e344d8241a"}