[package]
name = "legend_of_mierda"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.11"
bevy_ecs_ldtk = {version="0.8", features=["default", "derive", "atlas", "render"]}
bevy-inspector-egui = "0.19"
bevy_rapier2d = "0.22"
rand = "0.8.5"
pecs = "0.4"
